config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: {message: "comment can't be blank"}
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :body, presence: {message: "post can't be blank"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new()
    respond_to do |format|
      format.js { render template: 'comments/comment_modal.js.erb' }
    end
  end

  def create
    @post = Post.find(params[:post_id])
    begin
      @comment = @post.comments.new(comment_params)
      if @comment.save
        flash[:notice] = 'comment created'
      else
        flash[:notice] = 'Comment not created'
      end
    rescue Exception => e
      flash[:error] = e.message 
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to root_url, notice: 'Comment deleted'
  end
  private

    def comment_params
      params.require(:comment).permit( 
        :body
      )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    respond_to do |format|
      format.js { render template: 'posts/post_modal.js.erb' }
    end
    
  end

  def create
    @post = Post.new(post_params)
    begin
      if @post.save
        Pusher.trigger('posts-channel','new-post', {
          id: @post.id,
          title: @post.title,
          body: @post.body
        })
        flash[:notice] = 'Post created'
        # redirect_to root_url, notice: 'Created post'
      else
        flash[:notice] = 'Post not created'
        # redirect_to new_post_path, flash: { error: @post.errors.full_messages.to_sentence }
      end
    rescue Exception => e
      flash[:error] = e.message 
      # redirect_to new_post_path, flash: { error: e.message }
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    respond_to do |format|
      format.js { render template: 'posts/post_modal.js.erb' }
    end
  end

  def update
    begin
      @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to root_url, notice: 'updated post'
      else
        flash[:notice] = 'Post not updated'
        redirect_to edit_post_path, flash: { error: @post.errors.full_messages.to_sentence }
      end
    rescue Exception => e
      redirect_to edit_post_path, flash: { error: e.message }
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_url, notice: 'Post deleted'
  end

  private

    def post_params
      params.require(:post).permit(
        :title, 
        :body
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.row
  .col-md-12
    %em= comment.body
    %br
    %code= "Commented #{time_ago_in_words(comment.created_at)} ago"
    %br
      =link_to [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } do
        %i.fas.fa-trash-alt.bigger-130.fa-lg.text-danger
%hr

app/views/comments/_form.html.haml
.modal{id: 'modal-comment', role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %h5.modal-title comment
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', type: 'button'}
          %span{'aria-hidden' => 'true'} ×
      = form_for([@post, @post.comments.build], remote: true) do |form|
        .modal-body
          .form-group
            = form.label :body
            %br
            = form.text_area :body
        .modal-footer
          = form.button 'Add comment', type: :submit, class: 'btn btn-success'

app/views/comments/comment_modal.js.erb
$('<%= j render "form" %>').modal();

app/views/comments/create.js.erb
<% if @comment.errors.empty? %>
  // add the post, show alert and hide modal
  var comments_count = '.comments_count'+'<%= @post.id =%>'
  $('.comments'+'<%= @post.id =%>').append(' <%= j render "comment", comment: @comment %>');
  $(comments_count).empty();
  $(comments_count).html('<%= @post.comments.count =%>'+' comments');
  $('.alert-success').html('Comment successfuly created').show();
  $('#modal-comment').modal('hide');
<% else %>
  // show first error
  $('.alert-error').html('<%= @comment.errors.full_messages[0] %>').show;
<% end %>

app/views/home/index.html.haml
:javascript
  var pusher = new Pusher('9d4bf8552ac628416418', {
    cluster: 'us3',
    encrypted: true
  });

#container.top-buffer.wrapper
  .row
    .col-md-2
    .col-md-8
      %h3.text-center Feed
      %br
      = link_to 'Add post', new_post_path, remote: true, class: 'btn btn-outline-primary'
      %hr
    .col-md-2
  %br  
  .row
    .col-md-2
    #feed.col-md-8.feed
      -if @posts.empty?
        %h3.text-center there is no posts yet
      -else
        - @posts.each do |post|
          = render 'posts/post', post: post
    .col-md-2

:javascript
  var channel = pusher.subscribe('posts-channel');
  channel.bind('new-post', function(data) {
      let post_id = data.id
      let post_body = data.body;
      let post_title = data.title;

      let div = document.getElementById('feed');
      let new_content = document.createElement("div");
      new_content.innerHTML = `
          <div class="row">
              <div class="col-md-12">
                <h4 class="text-justify">${post_title}</h4>
                <hr/>
                <p class= 'text-justify'>${post_body}</p>
              </div>
          </div>`;
      div.insertBefore(new_content, div.firstChild);
  });

app/views/layouts/_header.html.haml
.row.head

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PostTest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "https://js.pusher.com/4.1/pusher.min.js"}

  %body
    .container-fluid
      = render 'layouts/header'
      -flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-info alert-#{message_type}")
      %br
      %br
      = yield

app/views/posts/_form.html.haml
.modal{id: 'modal-post', role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %h5.modal-title Post
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', type: 'button'}
          %span{'aria-hidden' => 'true'} ×
      = form_for @post, remote: true do |form|
        .modal-body
          .form-group
            = form.label :title
            %br
            = form.text_field :title
          .form-group
            = form.label :body
            %br
            = form.text_area :body
        .modal-footer
          = form.button 'Add post', type: :submit, class: 'btn btn-success'

app/views/posts/_post.html.haml
.row
  .col-md-12
    -unless post.title.nil?
      %h4.text-justify= post.title
    %hr
    %p.text-justify= post.body
.row
  .col-md-1
  .col-md-11
    .row
      .col-md-12
        %strong{class: "comments_count#{post.id}"}= "#{post.comments.count} comments"
    .row
      .col-md-12{class: "comments#{post.id}"}
        -unless post.comments.empty?
          -post.comments.each do |comment|
            = render 'comments/comment', comment: comment
    .row
      .col-md-12
        = link_to new_post_comment_path(post), remote: true do
          add
          %i.fas.fa-comment-dots.bigger-130.fa-lg.text-info
    %hr
.row
  .col-md-12
    %code= "Posted #{time_ago_in_words(post.created_at)} ago" 
    %br
    =link_to edit_post_path(post), remote: true do
      %i.fas.fa-pencil-alt.bigger-130.fa-lg.text-secondary
    =link_to post_path(post), method: :delete, data: { confirm: 'Are you sure?' } do
      %i.fas.fa-trash-alt.bigger-130.fa-lg.text-danger
%hr

app/views/posts/create.js.erb
<% if @post.errors.empty? %>
  // add the post, show alert and hide modal
  $('.feed').prepend(' <%= j render "post", post: @post %>');
  $('.alert-success').html('Post successfuly created').show();
  $('#modal-post').modal('hide');
<% else %>
  // show first error
  $('.alert-error').html('<%= @post.errors.full_messages[0] %>').show;
<% end %>

app/views/posts/post_modal.js.erb
$('<%= j render "form" %>').modal();